// middleware.ts
// ─────────────────────────────────────────────────────────────────────────────
// Next.js middleware — runs on every request BEFORE the page renders.
//
// WHAT IT DOES:
// Refreshes the Supabase session cookie so the user's auth token doesn't
// expire mid-session. Without this, the token would expire after 1 hour
// and the user would get logged out silently.
//
// WHY WE INLINE THE SUPABASE CLIENT HERE:
// Middleware runs in the Edge runtime — a lightweight V8 environment that
// doesn't support all Node.js APIs. Two specific constraints:
//   1. Can't import from lib/supabase-server.ts (it uses next/headers which
//      is not available in Edge runtime)
//   2. Can't import from lib/supabase.ts (createBrowserClient won't work
//      server-side — no window object)
// So we build the client inline, reading/writing the raw request/response cookies.
//
// THE ROUTE MATCHER:
// We exclude static files, images, and PWA assets to avoid running auth
// logic on every single asset request (would be very slow).
// ─────────────────────────────────────────────────────────────────────────────

import { NextResponse, type NextRequest } from 'next/server'
import { createServerClient, type CookieOptions } from '@supabase/ssr'

export async function middleware(request: NextRequest) {
  // Start with a plain "pass through" response
  let response = NextResponse.next({ request: { headers: request.headers } })

  // Skip auth refresh if Supabase isn't configured
  // (e.g. when running in demo mode without env vars)
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
  if (!supabaseUrl || !supabaseKey) return response

  // Build an Edge-compatible Supabase client that reads/writes cookies
  // directly on the NextRequest/NextResponse objects
  const supabase = createServerClient(supabaseUrl, supabaseKey, {
    cookies: {
      // Read a cookie from the incoming request
      get(name: string) {
        return request.cookies.get(name)?.value
      },
      // Write a cookie — must update BOTH the request (for this function)
      // and the response (so the browser receives the updated cookie)
      set(name: string, value: string, options: CookieOptions) {
        request.cookies.set({ name, value, ...options })
        response = NextResponse.next({ request: { headers: request.headers } })
        response.cookies.set({ name, value, ...options })
      },
      // Remove a cookie by setting it to empty string
      remove(name: string, options: CookieOptions) {
        request.cookies.set({ name, value: '', ...options })
        response = NextResponse.next({ request: { headers: request.headers } })
        response.cookies.set({ name, value: '', ...options })
      },
    },
  })

  // This call refreshes the session if the access token has expired.
  // Supabase will issue a new token using the refresh token stored in the cookie.
  // If both tokens are expired or invalid, getUser() returns null and the user
  // will be redirected to login by AuthGate.tsx on the client side.
  await supabase.auth.getUser()

  return response
}

// Runs middleware on all routes EXCEPT:
//   _next/static  — Next.js bundled JS/CSS (no auth needed)
//   _next/image   — Next.js image optimisation endpoint
//   favicon.ico   — Browser favicon
//   icons/        — PWA icons
//   manifest.json — PWA manifest
//   sw.js         — Service worker
//   workbox-*     — Service worker dependencies (generated by next-pwa)
export const config = {
  matcher: [
    '/((?!_next/static|_next/image|favicon.ico|icons/|manifest.json|sw.js|workbox-).*)',
  ],
}
